name       : perl-test-simple
version    : '1.302164'
release    : 10
source     :
    - https://cpan.metacpan.org/authors/id/E/EX/EXODIST/Test-Simple-1.302164.tar.gz : 50277b613f09cd52eb87b02c69ce0517b80080be8a8d80e1eda609479b0d6615
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Test2 - Framework for writing test tools that all work together.
homepage   : https://github.com/Test-More/test-more
description: |
    Test2 is a new testing framework produced by forking Test::Builder, completely refactoring it, adding many new features and capabilities.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
