name       : perl-test-simple
version    : 1.302120
release    : 1
source     :
    - https://cpan.metacpan.org/authors/id/E/EX/EXODIST/Test-Simple-1.302120.tar.gz : c82360092d4dacd6e3248b613fa00053072fe9cf55d022f1e0f427f51d04346c
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Test2 - Framework for writing test tools that all work together.
description: |
    Test2 is a new testing framework produced by forking Test::Builder, completely refactoring it, adding many new features and capabilities.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
